server:
  address: 0.0.0.0:502 #服务地址

mqtt:
  broker: 127.0.0.1:1883 #mqtt服务端地址
  username: root
  password: root
  topic_to_publish: gateway/attributes #发送主题
  topic_to_subscribe: plugin/modbus/#
  status_topic: device/status
  qos: 0 #qos

http_server:
  address: 0.0.0.0:503 #http服务地址

thingspanel:
  address: http://127.0.0.1:9999 #thingspanel服务地址

log: 
  # 日志级别 debug, info, warn, error, fatal, panic
  level: debug
