name: docker-image-latest

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: thingspanel/modbus-protocol-plugin:latest

    - name: Login to Aliyuncs Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.IMAGE_USER }}
        password: ${{ secrets.IMAGE_PASS }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub
      run: |
         skopeo copy docker://docker.io/thingspanel/modbus-protocol-plugin:latest docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/modbus-protocol-plugin:latest
